/*
 * Created on 7 jun 2017 ( Time 11:28:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.web.listitem;

import org.servicosGerais.bean.Cliente;
import org.servicosGerais.web.common.ListItem;

public class ClienteListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ClienteListItem(Cliente cliente) {
		super();

		this.value = ""
			 + cliente.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = cliente.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
