/*
 * Created on 7 jun 2017 ( Time 11:28:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.web.listitem;

import org.servicosGerais.bean.enun.TipoServico;
import org.servicosGerais.web.common.ListItem;

public class TipoServicoListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public TipoServicoListItem(TipoServico tipoServico) {
		super();

		this.value = ""
			 + TipoServico.valueOf(tipoServico.name());
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = tipoServico.getDescricao();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
