/*
 * Created on 7 jun 2017 ( Time 11:29:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.servicosGerais.bean.Cliente;
import org.servicosGerais.bean.jpa.ClienteEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ClienteServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ClienteServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ClienteEntity' to 'Cliente'
	 * @param clienteEntity
	 */
	public Cliente mapClienteEntityToCliente(ClienteEntity clienteEntity) {
		if(clienteEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Cliente cliente = map(clienteEntity, Cliente.class);

		return cliente;
	}
	
	/**
	 * Mapping from 'Cliente' to 'ClienteEntity'
	 * @param cliente
	 * @param clienteEntity
	 */
	public void mapClienteToClienteEntity(Cliente cliente, ClienteEntity clienteEntity) {
		if(cliente == null) {
			return;
		}

		//--- Generic mapping 
		map(cliente, clienteEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}