/*
 * Created on 7 jun 2017 ( Time 11:29:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.servicosGerais.bean.ServicoRoupas;
import org.servicosGerais.bean.jpa.ServicoRoupasEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ServicoRoupasServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ServicoRoupasServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ServicoRoupasEntity' to 'ServicoRoupas'
	 * @param servicoRoupasEntity
	 */
	public ServicoRoupas mapServicoRoupasEntityToServicoRoupas(ServicoRoupasEntity servicoRoupasEntity) {
		if(servicoRoupasEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ServicoRoupas servicoRoupas = map(servicoRoupasEntity, ServicoRoupas.class);

		return servicoRoupas;
	}
	
	/**
	 * Mapping from 'ServicoRoupas' to 'ServicoRoupasEntity'
	 * @param servicoRoupas
	 * @param servicoRoupasEntity
	 */
	public void mapServicoRoupasToServicoRoupasEntity(ServicoRoupas servicoRoupas, ServicoRoupasEntity servicoRoupasEntity) {
		if(servicoRoupas == null) {
			return;
		}

		//--- Generic mapping 
		map(servicoRoupas, servicoRoupasEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}