/*
 * Created on 7 jun 2017 ( Time 11:28:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.web.common;

public enum MessageType {
	
	SUCCESS,
	INFO,
	WARNING,
	DANGER;
	
	public String getCss() {
		return name().toLowerCase();
	}
	
}
