/*
 * Created on 7 jun 2017 ( Time 11:29:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.business.service;

import java.util.List;

import org.servicosGerais.bean.Cliente;

/**
 * Business Service Interface for entity Cliente.
 */
public interface ClienteService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Cliente findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Cliente> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Cliente save(Cliente entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Cliente update(Cliente entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Cliente create(Cliente entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
