/*
 * Created on 7 jun 2017 ( Time 11:29:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.business.service;

import java.util.List;

import org.servicosGerais.bean.ServicoRoupas;

/**
 * Business Service Interface for entity ServicoRoupas.
 */
public interface ServicoRoupasService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ServicoRoupas findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ServicoRoupas> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ServicoRoupas save(ServicoRoupas entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ServicoRoupas update(ServicoRoupas entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ServicoRoupas create(ServicoRoupas entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
