/*
 * Created on 7 jun 2017 ( Time 11:29:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.business.service;

import java.util.List;

import org.servicosGerais.bean.Servico;

/**
 * Business Service Interface for entity Servico.
 */
public interface ServicoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Servico findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Servico> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Servico save(Servico entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Servico update(Servico entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Servico create(Servico entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
