/*
 * Created on 7 jun 2017 ( Time 11:29:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.business.service.impl;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.List;

import org.servicosGerais.bean.Cliente;
import org.servicosGerais.bean.jpa.ClienteEntity;
import java.util.List;
import org.servicosGerais.business.service.mapping.ClienteServiceMapper;
import org.servicosGerais.data.repository.jpa.ClienteJpaRepository;
import org.servicosGerais.test.ClienteFactoryForTest;
import org.servicosGerais.test.ClienteEntityFactoryForTest;
import org.servicosGerais.test.MockValues;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

/**
 * Test : Implementation of ClienteService
 */
@RunWith(MockitoJUnitRunner.class)
public class ClienteServiceImplTest {

	@InjectMocks
	private ClienteServiceImpl clienteService;
	@Mock
	private ClienteJpaRepository clienteJpaRepository;
	@Mock
	private ClienteServiceMapper clienteServiceMapper;
	
	private ClienteFactoryForTest clienteFactoryForTest = new ClienteFactoryForTest();

	private ClienteEntityFactoryForTest clienteEntityFactoryForTest = new ClienteEntityFactoryForTest();

	private MockValues mockValues = new MockValues();
	
	@Test
	public void findById() {
		// Given
		Integer id = mockValues.nextInteger();
		
		ClienteEntity clienteEntity = clienteJpaRepository.findOne(id);
		
		Cliente cliente = clienteFactoryForTest.newCliente();
		when(clienteServiceMapper.mapClienteEntityToCliente(clienteEntity)).thenReturn(cliente);

		// When
		Cliente clienteFound = clienteService.findById(id);

		// Then
		assertEquals(cliente.getId(),clienteFound.getId());
	}

	@Test
	public void findAll() {
		// Given
		List<ClienteEntity> clienteEntitys = new ArrayList<ClienteEntity>();
		ClienteEntity clienteEntity1 = clienteEntityFactoryForTest.newClienteEntity();
		clienteEntitys.add(clienteEntity1);
		ClienteEntity clienteEntity2 = clienteEntityFactoryForTest.newClienteEntity();
		clienteEntitys.add(clienteEntity2);
		when(clienteJpaRepository.findAll()).thenReturn(clienteEntitys);
		
		Cliente cliente1 = clienteFactoryForTest.newCliente();
		when(clienteServiceMapper.mapClienteEntityToCliente(clienteEntity1)).thenReturn(cliente1);
		Cliente cliente2 = clienteFactoryForTest.newCliente();
		when(clienteServiceMapper.mapClienteEntityToCliente(clienteEntity2)).thenReturn(cliente2);

		// When
		List<Cliente> clientesFounds = clienteService.findAll();

		// Then
		assertTrue(cliente1 == clientesFounds.get(0));
		assertTrue(cliente2 == clientesFounds.get(1));
	}

	@Test
	public void create() {
		// Given
		Cliente cliente = clienteFactoryForTest.newCliente();

		ClienteEntity clienteEntity = clienteEntityFactoryForTest.newClienteEntity();
		when(clienteJpaRepository.findOne(cliente.getId())).thenReturn(null);
		
		clienteEntity = new ClienteEntity();
		clienteServiceMapper.mapClienteToClienteEntity(cliente, clienteEntity);
		ClienteEntity clienteEntitySaved = clienteJpaRepository.save(clienteEntity);
		
		Cliente clienteSaved = clienteFactoryForTest.newCliente();
		when(clienteServiceMapper.mapClienteEntityToCliente(clienteEntitySaved)).thenReturn(clienteSaved);

		// When
		Cliente clienteResult = clienteService.create(cliente);

		// Then
		assertTrue(clienteResult == clienteSaved);
	}

	@Test
	public void createKOExists() {
		// Given
		Cliente cliente = clienteFactoryForTest.newCliente();

		ClienteEntity clienteEntity = clienteEntityFactoryForTest.newClienteEntity();
		when(clienteJpaRepository.findOne(cliente.getId())).thenReturn(clienteEntity);

		// When
		Exception exception = null;
		try {
			clienteService.create(cliente);
		} catch(Exception e) {
			exception = e;
		}

		// Then
		assertTrue(exception instanceof IllegalStateException);
		assertEquals("already.exists", exception.getMessage());
	}

	@Test
	public void update() {
		// Given
		Cliente cliente = clienteFactoryForTest.newCliente();

		ClienteEntity clienteEntity = clienteEntityFactoryForTest.newClienteEntity();
		when(clienteJpaRepository.findOne(cliente.getId())).thenReturn(clienteEntity);
		
		ClienteEntity clienteEntitySaved = clienteEntityFactoryForTest.newClienteEntity();
		when(clienteJpaRepository.save(clienteEntity)).thenReturn(clienteEntitySaved);
		
		Cliente clienteSaved = clienteFactoryForTest.newCliente();
		when(clienteServiceMapper.mapClienteEntityToCliente(clienteEntitySaved)).thenReturn(clienteSaved);

		// When
		Cliente clienteResult = clienteService.update(cliente);

		// Then
		verify(clienteServiceMapper).mapClienteToClienteEntity(cliente, clienteEntity);
		assertTrue(clienteResult == clienteSaved);
	}

	@Test
	public void delete() {
		// Given
		Integer id = mockValues.nextInteger();

		// When
		clienteService.delete(id);

		// Then
		verify(clienteJpaRepository).delete(id);
		
	}

}
