/*
 * Created on 7 jun 2017 ( Time 11:28:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.servicosGerais.bean.ServicoRoupas;
import org.servicosGerais.business.service.ServicoRoupasService;
import org.servicosGerais.web.listitem.ServicoRoupasListItem;

/**
 * Spring MVC controller for 'ServicoRoupas' management.
 */
@Controller
public class ServicoRoupasRestController {

	@Resource
	private ServicoRoupasService servicoRoupasService;
	
	@RequestMapping( value="/items/servicoRoupas",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ServicoRoupasListItem> findAllAsListItems() {
		List<ServicoRoupas> list = servicoRoupasService.findAll();
		List<ServicoRoupasListItem> items = new LinkedList<ServicoRoupasListItem>();
		for ( ServicoRoupas servicoRoupas : list ) {
			items.add(new ServicoRoupasListItem( servicoRoupas ) );
		}
		return items;
	}
	
	@RequestMapping( value="/servicoRoupas",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ServicoRoupas> findAll() {
		return servicoRoupasService.findAll();
	}

	@RequestMapping( value="/servicoRoupas/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ServicoRoupas findOne(@PathVariable("id") Integer id) {
		return servicoRoupasService.findById(id);
	}
	
	@RequestMapping( value="/servicoRoupas",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ServicoRoupas create(@RequestBody ServicoRoupas servicoRoupas) {
		return servicoRoupasService.create(servicoRoupas);
	}

	@RequestMapping( value="/servicoRoupas/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ServicoRoupas update(@PathVariable("id") Integer id, @RequestBody ServicoRoupas servicoRoupas) {
		return servicoRoupasService.update(servicoRoupas);
	}

	@RequestMapping( value="/servicoRoupas/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		servicoRoupasService.delete(id);
	}
	
}
