/*
 * Created on 7 jun 2017 ( Time 11:29:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.servicosGerais.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "cliente"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="cliente", catalog="servicos_gerais" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ClienteEntity.countAll", query="SELECT COUNT(x) FROM ClienteEntity x" )
} )
public class ClienteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nome", nullable=false, length=255)
    private String     nome         ;

    @Column(name="telefone", nullable=false, length=12)
    private String     telefone     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="cliente", targetEntity=ServicoEntity.class)
    private List<ServicoEntity> listOfServico;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ClienteEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nome ( VARCHAR ) 
    public void setNome( String nome ) {
        this.nome = nome;
    }
    public String getNome() {
        return this.nome;
    }

    //--- DATABASE MAPPING : telefone ( VARCHAR ) 
    public void setTelefone( String telefone ) {
        this.telefone = telefone;
    }
    public String getTelefone() {
        return this.telefone;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfServico( List<ServicoEntity> listOfServico ) {
        this.listOfServico = listOfServico;
    }
    public List<ServicoEntity> getListOfServico() {
        return this.listOfServico;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nome);
        sb.append("|");
        sb.append(telefone);
        return sb.toString(); 
    } 

}
