/*
 * Created on 7 jun 2017 ( Time 11:29:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.servicosGerais.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "servico_roupas"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="servico_roupas", catalog="servicos_gerais" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ServicoRoupasEntity.countAll", query="SELECT COUNT(x) FROM ServicoRoupasEntity x" )
} )
public class ServicoRoupasEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    

    @Column(name="quantidade_pecas", nullable=false)
    private Integer    quantidadePecas ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="id", referencedColumnName="id", insertable=false, updatable=false)
    private ServicoEntity servico     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ServicoRoupasEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    

    //--- DATABASE MAPPING : quantidade_pecas ( INT ) 
    public void setQuantidadePecas( Integer quantidadePecas ) {
        this.quantidadePecas = quantidadePecas;
    }
    public Integer getQuantidadePecas() {
        return this.quantidadePecas;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setServico( ServicoEntity servico ) {
        this.servico = servico;
    }
    public ServicoEntity getServico() {
        return this.servico;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(quantidadePecas);
        return sb.toString(); 
    } 

}
