/*
 * Created on 7 jun 2017 ( Time 11:28:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Cliente implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 255 )
    private String nome;

    @NotNull
    @Size( min = 1, max = 12 )
    private String telefone;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNome( String nome ) {
        this.nome = nome;
    }
    public String getNome() {
        return this.nome;
    }

    public void setTelefone( String telefone ) {
        this.telefone = telefone;
    }
    public String getTelefone() {
        return this.telefone;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(nome);
        sb.append("|");
        sb.append(telefone);
        return sb.toString(); 
    } 


}
