/*
 * Created on 7 jun 2017 ( Time 11:28:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Servico implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Date dataEntrada;


    private Date dataSaida;

    @NotNull
    private Float valor;

    @NotNull
    @Size( min = 1, max = 300 )
    private String observacao;


    private Integer clienteId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDataEntrada( Date dataEntrada ) {
        this.dataEntrada = dataEntrada;
    }
    public Date getDataEntrada() {
        return this.dataEntrada;
    }

    public void setDataSaida( Date dataSaida ) {
        this.dataSaida = dataSaida;
    }
    public Date getDataSaida() {
        return this.dataSaida;
    }

    public void setValor( Float valor ) {
        this.valor = valor;
    }
    public Float getValor() {
        return this.valor;
    }

    public void setObservacao( String observacao ) {
        this.observacao = observacao;
    }
    public String getObservacao() {
        return this.observacao;
    }

    public void setClienteId( Integer clienteId ) {
        this.clienteId = clienteId;
    }
    public Integer getClienteId() {
        return this.clienteId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(dataEntrada);
        sb.append("|");
        sb.append(dataSaida);
        sb.append("|");
        sb.append(valor);
        sb.append("|");
        sb.append(observacao);
        sb.append("|");
        sb.append(clienteId);
        return sb.toString(); 
    } 


}
