/*
 * Created on 7 jun 2017 ( Time 11:28:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.servicosGerais.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class ServicoRoupas implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 15 )
    private String tipoServico;

    @NotNull
    private Integer quantidadePecas;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTipoServico( String tipoServico ) {
        this.tipoServico = tipoServico;
    }
    public String getTipoServico() {
        return this.tipoServico;
    }

    public void setQuantidadePecas( Integer quantidadePecas ) {
        this.quantidadePecas = quantidadePecas;
    }
    public Integer getQuantidadePecas() {
        return this.quantidadePecas;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(tipoServico);
        sb.append("|");
        sb.append(quantidadePecas);
        return sb.toString(); 
    } 


}
